### ISSUE TITLE
Calendar no longer shows up at top of Upcoming 

### ISSUE THREAD

**Issue by addisonr08** [ErikBoesen/Newlogy#28]
This is a noticeable navigational issue, keeping me from accessing a class specific calendar from the class page.

**Comment by ErikBoesen** [comment]
You're right, this was something I definitely didn't want to do. The update I'll push momentarily will fix this.

**Comment by ErikBoesen** [comment]
You're right, this was something I definitely didn't want to do. The update I'll push momentarily will fix this.
