### ISSUE TITLE
Change header to position:fixed

### ISSUE THREAD

**Issue by jamestrombo** [ErikBoesen/Newlogy#30]
....

**Comment by ErikBoesen** [comment]
When would this be useful? I feel like our screens are small enough already and taking off more screen space would be kind of a pain.

**Comment by ErikBoesen** [comment]
I'm actually going to add an option for this, so you will have access to that feature within a day or too.

**Comment by ErikBoesen** [comment]
I added a "floating header" option which does both of the things you asked. Let me know if I can fix anything else.
