### ISSUE TITLE
Add the ability to use this extension on other domains!

### ISSUE THREAD

**Issue by noahdotpy** [ErikBoesen/Newlogy#64]
My school uses a different domain than schoology.com, it would be very much appreciated if I could be able to use this extension on different domains of my choosing. Thanks!

**Comment by ErikBoesen** [comment]
Thanks for your comment! What domain does your school use? Because of the design of the Chrome Extensions API it's not really viable to make the extension activate on all domains, but if I have some information about the structure of your domain I may be able to work something out.

**Comment by noahdotpy** [comment]
I can not say the domain that my school uses as it would give personal info, thanks though.

**Comment by ErikBoesen** [comment]
Alright, well I can't enable the extension for a domain if I don't know what the domain is, sorry about that.
